language: node_js
sudo: required
dist: trusty
node_js:
  - "node"
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_script:
  - npm install -g polymer-cli
  - npm install -g codecov
script:
  - xvfb-run npm run test && npm run build
  - codecov
